name: Update Data

on: 
  schedule:
    - cron: '30 19 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.1'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: run python script
        run: python backend/Main.py
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backend/data.json
          git commit -m "Update data" -a
      
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
